# ---------- Stage 1: Build frontend ----------
FROM node:20-alpine AS node-builder

WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend .
RUN npm run build


# ---------- Stage 2: PHP Production ----------
FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    icu-dev oniguruma-dev libzip-dev \
 && docker-php-ext-install pdo pdo_mysql mbstring intl zip opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy Laravel source
COPY backend .

# Copy built assets
COPY --from=node-builder /app/public/build ./public/build

RUN composer install --no-dev --optimize-autoloader \
 && php artisan config:clear \
 && php artisan route:clear \
 && php artisan view:clear

COPY php.ini /usr/local/etc/php/conf.d/99-custom.ini

RUN chown -R www-data:www-data /var/www/html
